import relaxImg from "../images/relax-svgrepo-com.svg"
import profileImg from "../images/logo.jpg"
const container=document.querySelector(".container");
let home=function(){
    let header=document.createElement("div");
    header.id="header";
    let content=document.createElement("div");
    content.id="content";
    let todo=document.createElement("div");
    todo.id="todo";
    todo.textContent="Todo";
    let sideBar=document.createElement("div");
    sideBar.id="side";
    let profile=document.createElement("img");
    profile.id="profile";
    profile.src=profileImg;
    profile.onclick = function() {
        window.location.href = 'https://github.com/Gary-love';
    };
    let logo=document.createElement("div");
    logo.id="logo";
    logo.textContent="To do list";
    let inbox=document.createElement("div");
    inbox.id="inbox";
    inbox.textContent="Inbox";
    let today=document.createElement("div");
    today.id="today";
    today.textContent="Today";
    let  priority=document.createElement("div");
    priority.id="priority";
    priority.textContent="Priority";
    let high=document.createElement("div");
    high.id="high";
    high.textContent="High";
    let medium=document.createElement("div");
    medium.id="medium";
    medium.textContent="Medium";
    let low=document.createElement("div");
    low.id="low";
    low.textContent="Low";
    let image=document.createElement("img");
    image.src=relaxImg;
    image.id="img";
    let message=document.createElement("p");
    message.textContent="Nothing to Do Add some more tasks";
    let addBtn=document.createElement("div");
    addBtn.id="button";
    addBtn.textContent="+";
    header.appendChild(logo);
    header.appendChild(profile);
    sideBar.appendChild(inbox);
    sideBar.appendChild(today);
    sideBar.appendChild(priority);
    sideBar.appendChild(high);
    sideBar.appendChild(medium);
    sideBar.appendChild(low);
    content.appendChild(todo);
    content.appendChild(image);
    content.appendChild(message);
    content.appendChild(addBtn);
    container.appendChild(header);
    container.appendChild(sideBar);
    container.appendChild(content);
}
export default home;