import home from "./home";
import profileImg from "../images/logo.jpg";
const container = document.querySelector(".container");
let loadFist = () => {
  let content = document.createElement("div");
  content.id = "content";
  let header = document.createElement("div");
  header.id = "header";
  let sideBar = document.createElement("div");
  sideBar.id = "side";
  let profile = document.createElement("img");
  profile.id = "profile";
  profile.src = profileImg;
  profile.onclick = function () {
    window.location.href = "https://github.com/Gary-love";
  };
  let logo = document.createElement("div");
  logo.id = "logo";
  logo.textContent = "To do project";
  let today = document.createElement("div");
  today.id = "today";
  today.textContent = "Today";
  let project = document.createElement("div");
  project.id = "project";
  project.textContent = "Projects";
  let work = document.createElement("div");
  work.id = "work";
  work.classList.add("project");
  work.textContent = "work";
  let school = document.createElement("div");
  school.id = "school";
  school.classList.add("project");
  school.textContent = "school";
  let project1 = document.createElement("div");
  project1.id = "default";
  project1.classList.add("project");
  project1.textContent = "project1";
  let all = document.createElement("div");
  all.id = "all";
  all.classList.add("project");
  all.textContent = "All projects";
  let addProj = document.createElement("button");
  addProj.id = "add";
  addProj.textContent = "+";
  header.appendChild(logo);
  header.appendChild(profile);
  sideBar.appendChild(today);
  sideBar.appendChild(project);
  project.appendChild(all);
  project.appendChild(project1);
  project.appendChild(work);
  project.appendChild(school);
  project.appendChild(addProj);
  container.appendChild(header);
  container.appendChild(sideBar);
  container.appendChild(content);
  home();
  buildTaskDefault("cut the grass", "work");
  buildTaskDefault("go outside", "school");
};
let buildTaskDefault = (name, project) => {
  let content = document.querySelector("#content");
  let tasks = document.querySelector("#tasks");
  let task = document.createElement("div");
  task.classList.add("task");
  task.id = project;
  let input = document.createElement("input");
  input.type = "checkbox";
  input.classList.add("checkbox");
  task.appendChild(input);
  let label = document.createElement("label");
  label.textContent = name;
  task.appendChild(label);
  input.addEventListener("click", () => {
    task.remove();
  });
  tasks.appendChild(task);
  content.style.backgroundImage = "none";
};
export default loadFist;
