import beer from"../images/beer2.jpg";
import orange from"../images/orange.jpg";
import prime from"../images/prime1.jpg";
import burger from"../images/burger.jpg";
import salad from"../images/salad.jpg";
import pizza from"../images/pizza.jpg";
import iceCream from"../images/icecream1.jpg";
const content=document.querySelector("#content");
let menu=function(){
    let drinks=document.createElement("div");
    content.style=`
    overflow-y: auto; 
    max-height: 900px;
    `
    drinks.textContent="Our Drinks";
    drinks.id="drinks";
    let drink1=document.createElement("div");
    let drink2=document.createElement("div");
    let drink3=document.createElement("div");
    let food1=document.createElement("div");
    let food2=document.createElement("div");
    let food3=document.createElement("div");
    let drink1Pic=document.createElement("img");
    let drink2Pic=document.createElement("img");
    let drink3Pic=document.createElement("img");
    let drink1Disc=document.createElement("span");
    let drink2Disc=document.createElement("span");
    let drink3Disc=document.createElement("span");
    drink2Pic.id="drink2";
    drink3Pic.id="drink3";
    let side1=document.createElement("div");
    let iceCreamDis=document.createElement("span");
    let food1Disc=document.createElement("span");
    let food2Disc=document.createElement("span");
    let food3Disc=document.createElement("span");
    let food1Pic=document.createElement("img");
    let food2Pic=document.createElement("img");
    let food3Pic=document.createElement("img");
    drink1Pic.src=beer;
    drink2Pic.src=orange;
    drink3Pic.src=prime;
    drink1Pic.classList="pics";
    drink2Pic.classList="pics";
    drink3Pic.classList="pics";
    food1Pic.src=burger;
    food2Pic.src=salad;
    food3Pic.src=pizza;
    food1Pic.classList="pics";
    food2Pic.classList="pics";
    food3Pic.classList="pics";
    let food=document.createElement("div");
    food.classList="food";
    food.textContent="Come and try our amazing Food";
    let sides=document.createElement("div");
    sides.id="sides";
    sides.textContent="Sides";  
    let iceCreamPic=document.createElement("img");
    iceCreamPic.src=iceCream;
    iceCreamPic.classList="pics";
    drink1Disc.textContent="**Broken Skull Beer** is a bold lager inspired by \"Stone Cold\" Steve Austin. Brewed in Texas, it features a crisp, refreshing taste with a hint of citrus—perfect for fans who appreciate quality and attitude. The striking can showcases Austin's iconic skull logo, embodying his no-nonsense spirit. Whether celebrating a win or relaxing with friends, raise a toast and say, \"Hell yeah!\"";
    drink2Disc.textContent="**Orange Pineapple Beer** is a refreshing and fruity beer inspired by the classic pineapple-orange flavor. Made in California, it features a smooth, fruity taste with a hint of citrus—perfect for fans who appreciate quality and attitude. The striking can showcases Austin's iconic pineapple logo, embodying his no-nonsense spirit. Whether celebrating a win or relax";
    drink3Disc.textContent="**Prime Ribs Beer** is a bold lager inspired by the classic Prime Ribs dish. Brewed in Texas, it features a crisp, refreshing taste with a hint of citrus—perfect for fans who appreciate quality and attitude. The striking can showcases Austin's iconic Prime Ribs logo, embodying his no-nonsense spirit. Whether celebrating a win";
    food1Disc.textContent="\"The Slammin' Stack\" Get ready to rumble with this towering burger! A juicy beef patty piled high with crispy bacon, melted cheddar, and tangy BBQ sauce, all sandwiched between a toasted brioche bun. Topped with spicy jalapeños, this burger delivers a knockout punch of flavor!"
    food2Disc.textContent="\"The Powerbomb Pie\"Unleash the flavor with this heavyweight champion of pizzas! Loaded with pepperoni, smoky sausage, and gooey mozzarella, it’s topped with a kick of zesty marinara and fresh basil. One bite and you’ll be chanting for a rematch!";
    food3Disc.textContent="\"The Grappler's Greens\" Stay in shape like a true champ with this powerhouse salad! Fresh mixed greens, cherry tomatoes, and crunchy cucumbers are tossed with grilled chicken and a zesty vinaigrette. Packed with protein and flavor, it’s the perfect fuel for your next showdown!";
    iceCreamDis.textContent="In a surprising turn of events, CM Punk has traded in the wrestling ring for a scoop of ice cream at the Champion's Feast restaurant! With a smile and his signature rebellious spirit, Punk is handing out ice cream bars to excited fans and diners alike. Decked out in his classic \"Best in the World\" gear, he playfully encourages everyone to indulge, proving that even champions know how to sweeten the day. As he chats with fans and poses for photos, the atmosphere buzzes with energy, turning an ordinary dessert run into a memorable celebration of both wrestling and delicious treats!"
    drink1.appendChild(drink1Disc);
    drink2.appendChild(drink2Disc);
    drink3.appendChild(drink3Disc);
    food1.appendChild(food1Disc);
    food2.appendChild(food2Disc);
    food3.appendChild(food3Disc);
    food1.appendChild(food1Pic);
    food2.appendChild(food2Pic);
    food3.appendChild(food3Pic);
    food.appendChild(food1);
    food.appendChild(food2);
    food.appendChild(food3);
    drink1.appendChild(drink1Pic);
    drink2.appendChild(drink2Pic);
    drink3.appendChild(drink3Pic);
    drinks.appendChild(drink1);
    drinks.appendChild(drink2);
    drinks.appendChild(drink3);
    side1.appendChild(iceCreamDis);
    side1.appendChild(iceCreamPic);
    sides.appendChild(side1);
    content.appendChild(drinks);
    content.appendChild(food);
    content.appendChild(sides);
}
export default menu;